spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gechillge
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  jwt:
    secret: 7b7d20677fae43e2dd2b372cc275877527f37b782fdf8b35b01f3bfef072b629
    refresh-exp: 604800000 # 1?
    access-exp: 86400000 # 24??
logging:
  level:
    org:
      hibernate:
        # sql
        sql: debug
        type:
          descriptor:
            sql: trace

  springdoc:
    api-docs:
      enabled: true
      version: openapi_3_0
      path: /v3/api-docs

    default-consumes-media-type: application/json
    auto-tag-classes: true
    groups:
      enabled: false

    swagger-ui:
      operationsSorter: method
      tags-sorter: alpha
      path: /swagger-ui.html